language: ruby
rvm:
  - 3.0
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --white-list axure,education.github.com,intel.com,shodan.io,canva.com,www.getastra.com,algolia.com,datacamp.com
